
stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "echo OK"

c-lib-test-job:
  stage: build
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "cd stacktrek && clang -g -O1 -I . test.c -o test -lm && ./test"

unit-test-job:
  stage: test
  script:
    - echo TODO

compile-test-job:
  stage: test
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "dune runtest ./test/compile"

integration-test-job:
  stage: test
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "dune runtest ./test/integration"

nightly-bench-job:
  stage: test
  rules:
    - if: $BENCH
  script:
    # This command builds and runs not only Lexi programs, but also programs in other systems
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "opam init; opam switch create 5.3.0+trunk; opam install -y multicont; cd scripts && python bench.py --quick"