
stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - pwd
    - cd benchmark-programs/lexi 
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose -c make build

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose -c make test

