
stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "opam init -a && eval \$(opam env) && opam install . --deps-only --working-dir --yes && echo OK"

unit-test-job:
  stage: test
  script:
    - echo TODO

compile-test-job:
  stage: test
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "eval \$(opam env) && dune runtest ./test/compile"

integration-test-job:
  stage: test
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "eval \$(opam env) && dune runtest ./test/integration"