
stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:
  stage: build
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "echo OK"

unit-test-job:
  stage: test
  script:
    - echo TODO

compile-test-job:
  stage: test
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "dune runtest ./test/compile"

integration-test-job:
  stage: test
  script:
    - nix --extra-experimental-features "nix-command flakes" develop --print-build-logs --verbose --command bash -c "dune runtest ./test/integration"