#!/usr/bin/env python
import argparse
import subprocess
import tempfile
import os
import shutil

def run_commands(source_file, output_file):
    temp_dir = tempfile.mkdtemp()
    try:
        base_name = os.path.basename(source_file)
        temp_file = os.path.join(temp_dir, os.path.splitext(base_name)[0] + ".c")

        dune_command = ["dune", "exec", "sstal", "--", source_file, "-o", temp_file]
        subprocess.run(dune_command, check=True)

        clang_command = ["clang", "-g", "-O3", "-I", "./src/stacktrek", temp_file, "-o", output_file, "-lm"]
        subprocess.run(clang_command, check=True)
    finally:
        shutil.rmtree(temp_dir)

def main():
    parser = argparse.ArgumentParser(description="Compile lexa programs.")
    parser.add_argument("source_file", type=str, help="The source file to compile")
    parser.add_argument("-o", "--output", type=str, default="a.out", help="The binary output file")
    
    args = parser.parse_args()

    run_commands(args.source_file, args.output)

if __name__ == "__main__":
    main()
